[package]
name = "petsc-sys"
version = "0.1.0"
authors = ["ZackJorquera <zackary.jorquera@colorado.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpi = {git = "https://github.com/rsmpi/rsmpi.git", branch = "master"}

[build-dependencies]
cc = "1.0"
bindgen = "0.58"
pkg-config = "0.3"
