[package]
name = "ksp"
version = "0.1.0"
authors = ["ZackJorquera <jorquerazack@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ex1"
path = "src/ex1.rs"

[[bin]]
name = "ex2"
path = "src/ex2.rs"

[dependencies]
libffi-sys = { version = "1.1.1", features = ["system"] }
mpi = {git = "https://github.com/rsmpi/rsmpi.git", branch = "master", features = ["user-operations", "derive"]}
petsc-rs = { path = "../../" }
structopt = { version = "0.3", default-features = false }
